In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('C:/Users/Devanshi Gupta/Desktop/Projects/news.csv')

In [4]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [6]:
df.isnull().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [10]:
X = df.drop('label', axis=1)
X.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text  
0  Daniel Greenfield, a Shillman Journalism Fello...  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  
2  U.S. Secretary of State John F. Kerry said Mon...  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  
4  It's primary day in New York and front-runners...

In [12]:
Y = df.pop('label')
Y.head()

0    FAKE
1    FAKE
2    REAL
3    FAKE
4    REAL
Name: label, dtype: object

In [13]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
Y = lb.fit_transform(Y)

In [15]:
Y

array([0, 0, 1, ..., 0, 1, 1])

In [21]:
print("X_shape :" + str(X.shape))
print("Y_shape :" + str(Y.shape))

X_shape :(6335, 3)
Y_shape :(6335,)


In [24]:
import tensorflow as tf

tf.__version__

'1.13.1'

In [26]:
from tensorflow.keras.models import Sequential
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

In [27]:
from tensorflow.keras.layers import Embedding

In [28]:
voc_size = 5000

### ONE HOT REPRESENTATION

In [30]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['title'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)


[nltk_data] Downloading package stopwords to C:\Users\Devanshi
[nltk_data]     Gupta\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [31]:
corpus

['smell hillari fear',
 'watch exact moment paul ryan commit polit suicid trump ralli video',
 'kerri go pari gestur sympathi',
 'berni support twitter erupt anger dnc tri warn',
 'battl new york primari matter',
 'tehran usa',
 'girl horrifi watch boyfriend left facetim',
 'britain schindler die',
 'fact check trump clinton command chief forum',
 'iran reportedli make new push uranium concess nuclear talk',
 'three clinton iowa glimps fire elud hillari clinton campaign',
 'donald trump shockingli weak deleg game somehow got even wors',
 'strong solar storm tech risk today news oct video',
 'way america prepar world war',
 'trump take cruz lightli',
 'women lead differ',
 'shock michel obama hillari caught glamor date rape promot',
 'hillari clinton huge troubl america notic sick thing hidden pictur liberti writer news',
 'iran bill obama like',
 'chart explain everyth need know partisanship america',
 'slipperi slope trump propos ban muslim',
 'episod sunday wire hail deplor special g

In [32]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[1524, 1699, 1671],
 [2599, 4581, 428, 4597, 1547, 2247, 397, 4123, 3422, 4927, 2249],
 [2201, 2168, 2623, 1120, 2802],
 [2258, 4687, 1804, 2035, 4446, 3319, 376, 1380],
 [2607, 3003, 1220, 2138, 2652],
 [4603, 1974],
 [4563, 1819, 2599, 1956, 1112, 1103],
 [3207, 2277, 2845],
 [1874, 2494, 3422, 984, 592, 1491, 1909],
 [4148, 2893, 2903, 3003, 2615, 1305, 2105, 2508, 4395],
 [3271, 984, 4721, 4152, 2367, 4861, 1699, 984, 2906],
 [3521, 3422, 3795, 2155, 516, 3577, 644, 2453, 750, 1733],
 [2480, 3396, 1119, 3418, 4030, 1458, 1186, 1785, 2249],
 [2995, 1081, 3662, 2820, 1369],
 [3422, 3425, 4210, 1148],
 [1810, 1880, 3016],
 [4529, 514, 1257, 1699, 3002, 592, 4727, 3491, 4154],
 [1699, 984, 956, 3221, 1081, 4121, 4481, 3921, 4510, 4029, 4559, 3578, 1186],
 [4148, 3696, 1257, 398],
 [2338, 3167, 695, 1377, 1549, 4072, 1081],
 [402, 107, 3422, 4603, 255, 1115],
 [2361, 4422, 3773, 2828, 366, 3482, 2583, 4900, 1385],
 [1699, 984, 2903, 561, 2328, 417, 1855],
 [3003, 2775, 3007, 2996, 1113

In [33]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1524 1699 1671]
 [   0    0    0 ... 3422 4927 2249]
 [   0    0    0 ... 2623 1120 2802]
 ...
 [   0    0    0 ... 3559 3199  381]
 [   0    0    0 ... 3622  174 3811]
 [   0    0    0 ... 4856 3422 2652]]


In [34]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0, 1524, 1699, 1671])

In [35]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [36]:
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               112800    
_________________________________________________________________
dropout (Dropout)            (None, 200)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 201       
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [38]:
len(embedded_docs),Y.shape

(6335, (6335,))

In [40]:
import numpy as np
X_final=np.array(embedded_docs)
Y_final=np.array(Y)

In [41]:
X_final.shape,Y_final.shape

((6335, 20), (6335,))

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_final, Y_final, test_size=0.33, random_state=42)

In [44]:
model1.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=10,batch_size=64)

Train on 4244 samples, validate on 2091 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/10
4244/4244 [==============================] - 31s 7ms/sample - loss: 0.6514 - acc: 0.6110 - val_loss: 0.5884 - val_acc: 0.7374
Epoch 2/10
4244/4244 [==============================] - 14s 3ms/sample - loss: 0.3849 - acc: 0.8334 - val_loss: 0.4838 - val_acc: 0.7767
Epoch 3/10
4244/4244 [==============================] - 14s 3ms/sample - loss: 0.2555 - acc: 0.8984 - val_loss: 0.5608 - val_acc: 0.7786
Epoch 4/10
4244/4244 [==============================] - 14s 3ms/sample - loss: 0.1837 - acc: 0.9321 - val_loss: 0.6325 - val_acc: 0.7714
Epoch 5/10
4244/4244 [==============================] - 14s 3ms/sample - loss: 0.1456 - acc: 0.9505 - val_loss: 0.8223 - val_acc: 0.7508
Epoch 6/10
4244/4244 [==============================] - 14s 3ms/sample - loss: 0.1235 - acc: 0.9574 - val_loss: 0.8072 - val_acc: 0.7513
Epoch 7/10
4244/4244 [==============================] - 15s 3ms/sample - loss: 0.0

In [45]:
y_pred1=model1.predict_classes(X_test)

In [46]:
from sklearn.metrics import confusion_matrix

In [48]:
confusion_matrix(Y_test,y_pred1)

array([[809, 262],
       [269, 751]], dtype=int64)

In [49]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred1)

0.7460545193687231

In [50]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.75      0.76      0.75      1071
           1       0.74      0.74      0.74      1020

    accuracy                           0.75      2091
   macro avg       0.75      0.75      0.75      2091
weighted avg       0.75      0.75      0.75      2091

